version: '3'
services:
#  redis:
#   image: redis:alpine
#    ports:
#     - "${REDIS_PORT}:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSW}
    ports:
      - "${DB_PORT}:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data