"""Add new tables or modify existing ones

Revision ID: 0aea52ef804a
Revises: 472d9caee799
Create Date: 2023-11-17 11:27:21.775586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aea52ef804a'
down_revision: Union[str, None] = '472d9caee799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('pdfs', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('pdfs', 'id')
    # ### end Alembic commands ###
