"""Add new tables or modify existing ones

Revision ID: 128d3003d310
Revises: 1de6d4da2d47
Create Date: 2023-11-17 05:57:15.410464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128d3003d310'
down_revision: Union[str, None] = '1de6d4da2d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('pdfs_owner_id_fkey', 'pdfs', type_='foreignkey')
    op.create_foreign_key(None, 'pdfs', 'users', ['user_id'], ['id'])
    op.drop_column('pdfs', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pdfs', type_='foreignkey')
    op.create_foreign_key('pdfs_owner_id_fkey', 'pdfs', 'users', ['owner_id'], ['id'])
    op.drop_column('pdfs', 'user_id')
    # ### end Alembic commands ###
