"""Add new tables or modify existing ones

Revision ID: 1de6d4da2d47
Revises: cee451df458a
Create Date: 2023-11-17 05:54:43.943947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de6d4da2d47'
down_revision: Union[str, None] = 'cee451df458a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pdfs_user_id_fkey', 'pdfs', type_='foreignkey')
    op.drop_column('pdfs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pdfs_user_id_fkey', 'pdfs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
