"""empty message

Revision ID: 32334f9fb04e
Revises: 76647c1e0400
Create Date: 2023-11-21 04:56:58.293080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32334f9fb04e'
down_revision: Union[str, None] = '76647c1e0400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pdfs_user_id_fkey', 'pdfs', type_='foreignkey')
    op.create_foreign_key(None, 'pdfs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdfs', type_='foreignkey')
    op.create_foreign_key('pdfs_user_id_fkey', 'pdfs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
