"""Add new tables or modify existing ones

Revision ID: 472d9caee799
Revises: 128d3003d310
Create Date: 2023-11-17 11:22:58.679243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472d9caee799'
down_revision: Union[str, None] = '128d3003d310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('file_id', sa.Integer(), nullable=False))
    op.drop_column('pdfs', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('pdfs', 'file_id')
    # ### end Alembic commands ###
