"""Add new tables or modify existing ones

Revision ID: 5a2a642d43bd
Revises: 309f8a88b7b8
Create Date: 2023-11-16 21:00:08.893962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2a642d43bd'
down_revision: Union[str, None] = '309f8a88b7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.add_column('pdfs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('pdfs', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_pdfs_filename', table_name='pdfs')
    op.drop_index('ix_pdfs_id', table_name='pdfs')
    op.create_foreign_key(None, 'pdfs', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'pdfs', type_='foreignkey')
    op.create_index('ix_pdfs_id', 'pdfs', ['id'], unique=False)
    op.create_index('ix_pdfs_filename', 'pdfs', ['filename'], unique=False)
    op.alter_column('pdfs', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('pdfs', 'user_id')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
