"""Add new tables or modify existing ones

Revision ID: 5fa5e6050b8f
Revises: ec0806f7461a
Create Date: 2023-11-16 22:07:06.038471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa5e6050b8f'
down_revision: Union[str, None] = 'ec0806f7461a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
