"""Add new tables or modify existing ones

Revision ID: 861c21397a7a
Revises: aee7546c1ed1
Create Date: 2023-11-16 21:30:06.169933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861c21397a7a'
down_revision: Union[str, None] = 'aee7546c1ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
