"""Add new tables or modify existing ones

Revision ID: 934b6d78c9b9
Revises: 0d66ec5623c3
Create Date: 2023-11-16 22:27:49.648674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934b6d78c9b9'
down_revision: Union[str, None] = '0d66ec5623c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
