"""create pdfs table

Revision ID: 9b0447d1431c
Revises: 0c0994593f63
Create Date: 2023-11-11 18:48:38.940784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0447d1431c'
down_revision: Union[str, None] = '0c0994593f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdfs_filename'), 'pdfs', ['filename'], unique=False)
    op.create_index(op.f('ix_pdfs_id'), 'pdfs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdfs_id'), table_name='pdfs')
    op.drop_index(op.f('ix_pdfs_filename'), table_name='pdfs')
    op.drop_table('pdfs')
    # ### end Alembic commands ###
