"""Add new tables or modify existing ones

Revision ID: 9f4b3c77bf7d
Revises: 6932241f43e0
Create Date: 2023-11-16 21:49:27.686512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4b3c77bf7d'
down_revision: Union[str, None] = '6932241f43e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
