"""Add new tables or modify existing ones

Revision ID: aee7546c1ed1
Revises: 5a2a642d43bd
Create Date: 2023-11-16 21:10:36.246036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee7546c1ed1'
down_revision: Union[str, None] = '5a2a642d43bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
