"""Cascade deletion of history by user_id

Revision ID: c35df1d32662
Revises: 32334f9fb04e
Create Date: 2023-11-21 06:41:41.019690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35df1d32662'
down_revision: Union[str, None] = '32334f9fb04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('histories_user_id_fkey', 'histories', type_='foreignkey')
    op.create_foreign_key(None, 'histories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.create_foreign_key('histories_user_id_fkey', 'histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
