"""Add new tables or modify existing ones

Revision ID: cee451df458a
Revises: e03da8ef70b2
Create Date: 2023-11-17 05:52:26.506310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee451df458a'
down_revision: Union[str, None] = 'e03da8ef70b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pdfs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdfs', type_='foreignkey')
    op.drop_column('pdfs', 'user_id')
    # ### end Alembic commands ###
