"""Add new tables or modify existing ones

Revision ID: ec0806f7461a
Revises: 9f4b3c77bf7d
Create Date: 2023-11-16 21:50:13.924485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0806f7461a'
down_revision: Union[str, None] = '9f4b3c77bf7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
